## Get cik list

In [1]:
import pandas as pd
import html5lib
import bs4

In [22]:
# Install related packages if 
# ! pip install --user html5lib
# ! pip install --user bs4

Requirement already satisfied: bs4 in ./.local/lib/python3.6/site-packages (0.0.1)
Requirement already satisfied: beautifulsoup4 in ./.local/lib/python3.6/site-packages (from bs4) (4.8.2)
Requirement already satisfied: soupsieve>=1.2 in ./.local/lib/python3.6/site-packages (from beautifulsoup4->bs4) (1.9.5)

In [2]:
table = pd.read_html("https://en.wikipedia.org/wiki/List_of_S%26P_500_companies",header =0, flavor = 'bs4')

In [5]:
!pwd

/home/users/lijx

In [212]:
table[0]

,Symbol,Security,SEC filings,GICS Sector,GICS Sub Industry,Headquarters Location,Date first added,CIK,Founded
0,MMM,3M Company,reports,Industrials,Industrial Conglomerates,"St. Paul, Minnesota",NaN,66740,1902
1,ABT,Abbott Laboratories,reports,Health Care,Health Care Equipment,"North Chicago, Illinois",1964-03-31,1800,1888
2,ABBV,AbbVie Inc.,reports,Health Care,Pharmaceuticals,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
3,ABMD,ABIOMED Inc,reports,Health Care,Health Care Equipment,"Danvers, Massachusetts",2018-05-31,815094,1981
4,ACN,Accenture plc,reports,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
5,ATVI,Activision Blizzard,reports,Communication Services,Interactive Home Entertainment,"Santa Monica, California",2015-08-31,718877,2008
6,ADBE,Adobe Systems Inc,reports,Information Technology,Application Software,"San Jose, California",1997-05-05,796343,1982
7,AMD,Advanced Micro Devices Inc,reports,Information Technology,Semiconductors,"Santa Clara, California",2017-03-20,2488,1969
8,AAP,Advance Auto Parts,reports,Consumer Discretionary,Automotive Retail,"Raleigh, North Carolina",2015-07-09,1158449,1932
9,AES,AES Corp,reports,Utilities,Independent Power Producers & Energy Traders,"Arlington, Virginia",1998-10-02,874761,1981
10,AFL,AFLAC Inc,reports,Financials,Life & Health Insurance,"Columbus, Georgia",1999-05-28,4977,1955
11,A,Agilent Technologies Inc,reports,Health Care,Health Care Equipment,"Santa Clara, California",2000-06-05,1090872,1999
12,APD,Air Products & Chemicals Inc,reports,Materials,Industrial Gases,"Allentown, Pennsylvania",1985-04-30,2969,1940
13,AKAM,Akamai Technologies Inc,reports,Information Technology,Internet Services & Infrastructure,"Cambridge, Massachusetts",2007-07-12,1086222,1998
14,ALK,Alaska Air Group Inc,reports,Industrials,Airlines,"Seattle, Washington",2016-05-13,766421,1985
15,ALB,Albemarle Corp,reports,Materials,Specialty Chemicals,"Charlotte, North Carolina",2016-07-01,915913,1994
16,ARE,Alexandria Real Estate Equities,reports,Real Estate,Office REITs,"Pasadena, California",2017-03-20,1035443,1994
17,ALXN,Alexion Pharmaceuticals,reports,Health Care,Biotechnology,"Boston, Massachusetts",2012-05-25,899866,1992
18,ALGN,Align Technology,reports,Health Care,Health Care Supplies,"San Jose, California",2017-06-19,1097149,1997
19,ALLE,Allegion,reports,Industrials,Building Products,"Dublin, Ireland",2013-12-02,1579241,1908
20,AGN,"Allergan, plc",reports,Health Care,Pharmaceuticals,"Dublin, Ireland",1999-04-12,1578845,1983
21,ADS,Alliance Data Systems,reports,Information Technology,Data Processing & Outsourced Services,"Plano, Texas",2013-12-23,1101215,1996
22,LNT,Alliant Energy Corp,reports,Utilities,Electric Utilities,"Madison, Wisconsin",2016-07-01,352541,1917
23,ALL,Allstate Corp,reports,Financials,Property & Casualty Insurance,"Northfield Township, Illinois",1995-07-13,899051,1931
24,GOOGL,Alphabet Inc Class A,reports,Communication Services,Interactive Media & Services,"Mountain View, California",2014-04-03,1652044,1998
25,GOOG,Alphabet Inc Class C,reports,Communication Services,Interactive Media & Services,"Mountain View, California",2006-04-03,1652044,1998
26,MO,Altria Group Inc,reports,Consumer Staples,Tobacco,"Richmond, Virginia",NaN,764180,1985
27,AMZN,Amazon.com Inc.,reports,Consumer Discretionary,Internet & Direct Marketing Retail,"Seattle, Washington",2005-11-18,1018724,1994
28,AMCR,Amcor plc,reports,Materials,Paper Packaging,"Warmley, Bristol, United Kingdom",2019-06-07,1748790,NaN
29,AEE,Ameren Corp,reports,Utilities,Multi-Utilities,"St. Louis, Missouri",1991-09-19,1002910,1902
...,...,...,...,...,...,...,...,...,...
475,VNO,Vornado Realty Trust,reports,Real Estate,Office REITs,"New York, New York",NaN,899689,NaN
476,VMC,Vulcan Materials,reports,Materials,Construction Materials,"Birmingham, Alabama",1999-06-30,1396009,NaN
477,WRB,W. R. Berkley Corporation,reports,Financials,Property & Casualty Insurance,"Greenwich, Connecticut",2019-12-05,11544,1967
478,WAB,Wabtec Corporation,reports,Industrials,Construction Machinery & Heavy Trucks,"Wilmerding, Pennsylvania",2019-02-27,943452,NaN
479,WMT,Walmart,reports,Consumer Staples,Hypermarkets & Super Centers,"Bentonville, Arkansas",1982-08-31,104169,NaN
480,WBA,Walgreens Boots Alliance,reports,Consumer Staples,Drug Retail,"Deerfield, Illinois",1979-12-31,1618921,NaN
481,DIS,The Walt Disney Company,reports,Communication Services,Movies & Entertainment,"Burbank, California",1976-06-30,1001039,NaN
482,WM,Waste Management Inc.,reports,Industrials,Environmental & Facilities Services,"Houston, Texas",NaN,823768,1968
483,WAT,Waters Corporation,reports,Health Care,Health Care Distributors,"Milford, Massachusetts",NaN,1000697,1958
484,WEC,Wec Energy Group Inc,reports,Utilities,Electric Utilities,"Milwaukee, Wisconsin",2008-10-31,783325,NaN
485,WCG,WellCare,reports,Health Care,Managed Health Care,"Tampa, Florida",1985,1279363,NaN
486,WFC,Wells Fargo,reports,Financials,Diversified Banks,"San Francisco, California",1976-06-30,72971,NaN
487,WELL,Welltower Inc.,reports,Real Estate,Health Care REITs,"Toledo, Ohio",2009-01-30,766704,NaN
488,WDC,Western Digital,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Irvine, California",2009-07-01,106040,NaN
489,WU,Western Union Co,reports,Information Technology,Data Processing & Outsourced Services,"Englewood, Colorado",NaN,1365135,1851
490,WRK,WestRock,reports,Materials,Paper Packaging,"Richmond, Virginia",NaN,1636023,NaN
491,WY,Weyerhaeuser,reports,Real Estate,Specialized REITs,"Federal Way, Washington",NaN,106535,NaN
492,WHR,Whirlpool Corp.,reports,Consumer Discretionary,Household Appliances,"Benton Harbor, Michigan",NaN,106640,1911
493,WMB,Williams Cos.,reports,Energy,Oil & Gas Storage & Transportation,"Tulsa, Oklahoma",1975-03-31,107263,NaN
494,WLTW,Willis Towers Watson,reports,Financials,Insurance Brokers,"London, United Kingdom",2016-01-05,1140536,NaN
495,WYNN,Wynn Resorts Ltd,reports,Consumer Discretionary,Casinos & Gaming,"Paradise, Nevada",2008-11-14,1174922,NaN
496,XEL,Xcel Energy Inc,reports,Utilities,Multi-Utilities,"Minneapolis, Minnesota",NaN,72903,1909
497,XRX,Xerox,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Norwalk, Connecticut",NaN,108772,1906
498,XLNX,Xilinx,reports,Information Technology,Semiconductors,"San Jose, California",1999-11-08,743988,NaN
499,XYL,Xylem Inc.,reports,Industrials,Industrial Machinery,"White Plains, New York",2011-11-01,1524472,NaN
500,YUM,Yum! Brands Inc,reports,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,NaN
501,ZBRA,Zebra Technologies,reports,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
502,ZBH,Zimmer Biomet Holdings,reports,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,NaN
503,ZION,Zions Bancorp,reports,Financials,Regional Banks,"Salt Lake City, Utah",2001-06-22,109380,NaN
504,ZTS,Zoetis,reports,Health Care,Pharmaceuticals,"Florham Park, New Jersey",2013-06-21,1555280,NaN

In [213]:
table[0]["CIK"].nunique()

500

In [214]:
table[0][table[0]["CIK"].duplicated()]

,Symbol,Security,SEC filings,GICS Sector,GICS Sub Industry,Headquarters Location,Date first added,CIK,Founded
25,GOOG,Alphabet Inc Class C,reports,Communication Services,Interactive Media & Services,"Mountain View, California",2006-04-03,1652044,1998
150,DISCK,Discovery Inc. Class C,reports,Communication Services,Broadcasting,"Silver Spring, Maryland",2014-08-07,1437107,NaN
205,FOX,Fox Corporation Class B,reports,Communication Services,Movies & Entertainment,"New York, New York",2015-09-18,1308161,NaN
341,NWS,News Corp. Class B,reports,Communication Services,Publishing,"New York, New York",2015-09-18,1564708,NaN
456,UA,Under Armour Class C,reports,Consumer Discretionary,"Apparel, Accessories & Luxury Goods","Baltimore, Maryland",2014-05-01,1336917,NaN

In [215]:
table_1 = table[0]

In [216]:
table_2 = table_1.drop(table_1.index[[25,150,205,341,456]])

In [217]:
table_2

,Symbol,Security,SEC filings,GICS Sector,GICS Sub Industry,Headquarters Location,Date first added,CIK,Founded
0,MMM,3M Company,reports,Industrials,Industrial Conglomerates,"St. Paul, Minnesota",NaN,66740,1902
1,ABT,Abbott Laboratories,reports,Health Care,Health Care Equipment,"North Chicago, Illinois",1964-03-31,1800,1888
2,ABBV,AbbVie Inc.,reports,Health Care,Pharmaceuticals,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
3,ABMD,ABIOMED Inc,reports,Health Care,Health Care Equipment,"Danvers, Massachusetts",2018-05-31,815094,1981
4,ACN,Accenture plc,reports,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
5,ATVI,Activision Blizzard,reports,Communication Services,Interactive Home Entertainment,"Santa Monica, California",2015-08-31,718877,2008
6,ADBE,Adobe Systems Inc,reports,Information Technology,Application Software,"San Jose, California",1997-05-05,796343,1982
7,AMD,Advanced Micro Devices Inc,reports,Information Technology,Semiconductors,"Santa Clara, California",2017-03-20,2488,1969
8,AAP,Advance Auto Parts,reports,Consumer Discretionary,Automotive Retail,"Raleigh, North Carolina",2015-07-09,1158449,1932
9,AES,AES Corp,reports,Utilities,Independent Power Producers & Energy Traders,"Arlington, Virginia",1998-10-02,874761,1981
10,AFL,AFLAC Inc,reports,Financials,Life & Health Insurance,"Columbus, Georgia",1999-05-28,4977,1955
11,A,Agilent Technologies Inc,reports,Health Care,Health Care Equipment,"Santa Clara, California",2000-06-05,1090872,1999
12,APD,Air Products & Chemicals Inc,reports,Materials,Industrial Gases,"Allentown, Pennsylvania",1985-04-30,2969,1940
13,AKAM,Akamai Technologies Inc,reports,Information Technology,Internet Services & Infrastructure,"Cambridge, Massachusetts",2007-07-12,1086222,1998
14,ALK,Alaska Air Group Inc,reports,Industrials,Airlines,"Seattle, Washington",2016-05-13,766421,1985
15,ALB,Albemarle Corp,reports,Materials,Specialty Chemicals,"Charlotte, North Carolina",2016-07-01,915913,1994
16,ARE,Alexandria Real Estate Equities,reports,Real Estate,Office REITs,"Pasadena, California",2017-03-20,1035443,1994
17,ALXN,Alexion Pharmaceuticals,reports,Health Care,Biotechnology,"Boston, Massachusetts",2012-05-25,899866,1992
18,ALGN,Align Technology,reports,Health Care,Health Care Supplies,"San Jose, California",2017-06-19,1097149,1997
19,ALLE,Allegion,reports,Industrials,Building Products,"Dublin, Ireland",2013-12-02,1579241,1908
20,AGN,"Allergan, plc",reports,Health Care,Pharmaceuticals,"Dublin, Ireland",1999-04-12,1578845,1983
21,ADS,Alliance Data Systems,reports,Information Technology,Data Processing & Outsourced Services,"Plano, Texas",2013-12-23,1101215,1996
22,LNT,Alliant Energy Corp,reports,Utilities,Electric Utilities,"Madison, Wisconsin",2016-07-01,352541,1917
23,ALL,Allstate Corp,reports,Financials,Property & Casualty Insurance,"Northfield Township, Illinois",1995-07-13,899051,1931
24,GOOGL,Alphabet Inc Class A,reports,Communication Services,Interactive Media & Services,"Mountain View, California",2014-04-03,1652044,1998
26,MO,Altria Group Inc,reports,Consumer Staples,Tobacco,"Richmond, Virginia",NaN,764180,1985
27,AMZN,Amazon.com Inc.,reports,Consumer Discretionary,Internet & Direct Marketing Retail,"Seattle, Washington",2005-11-18,1018724,1994
28,AMCR,Amcor plc,reports,Materials,Paper Packaging,"Warmley, Bristol, United Kingdom",2019-06-07,1748790,NaN
29,AEE,Ameren Corp,reports,Utilities,Multi-Utilities,"St. Louis, Missouri",1991-09-19,1002910,1902
30,AAL,American Airlines Group,reports,Industrials,Airlines,"Fort Worth, Texas",2015-03-23,6201,1934
...,...,...,...,...,...,...,...,...,...
475,VNO,Vornado Realty Trust,reports,Real Estate,Office REITs,"New York, New York",NaN,899689,NaN
476,VMC,Vulcan Materials,reports,Materials,Construction Materials,"Birmingham, Alabama",1999-06-30,1396009,NaN
477,WRB,W. R. Berkley Corporation,reports,Financials,Property & Casualty Insurance,"Greenwich, Connecticut",2019-12-05,11544,1967
478,WAB,Wabtec Corporation,reports,Industrials,Construction Machinery & Heavy Trucks,"Wilmerding, Pennsylvania",2019-02-27,943452,NaN
479,WMT,Walmart,reports,Consumer Staples,Hypermarkets & Super Centers,"Bentonville, Arkansas",1982-08-31,104169,NaN
480,WBA,Walgreens Boots Alliance,reports,Consumer Staples,Drug Retail,"Deerfield, Illinois",1979-12-31,1618921,NaN
481,DIS,The Walt Disney Company,reports,Communication Services,Movies & Entertainment,"Burbank, California",1976-06-30,1001039,NaN
482,WM,Waste Management Inc.,reports,Industrials,Environmental & Facilities Services,"Houston, Texas",NaN,823768,1968
483,WAT,Waters Corporation,reports,Health Care,Health Care Distributors,"Milford, Massachusetts",NaN,1000697,1958
484,WEC,Wec Energy Group Inc,reports,Utilities,Electric Utilities,"Milwaukee, Wisconsin",2008-10-31,783325,NaN
485,WCG,WellCare,reports,Health Care,Managed Health Care,"Tampa, Florida",1985,1279363,NaN
486,WFC,Wells Fargo,reports,Financials,Diversified Banks,"San Francisco, California",1976-06-30,72971,NaN
487,WELL,Welltower Inc.,reports,Real Estate,Health Care REITs,"Toledo, Ohio",2009-01-30,766704,NaN
488,WDC,Western Digital,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Irvine, California",2009-07-01,106040,NaN
489,WU,Western Union Co,reports,Information Technology,Data Processing & Outsourced Services,"Englewood, Colorado",NaN,1365135,1851
490,WRK,WestRock,reports,Materials,Paper Packaging,"Richmond, Virginia",NaN,1636023,NaN
491,WY,Weyerhaeuser,reports,Real Estate,Specialized REITs,"Federal Way, Washington",NaN,106535,NaN
492,WHR,Whirlpool Corp.,reports,Consumer Discretionary,Household Appliances,"Benton Harbor, Michigan",NaN,106640,1911
493,WMB,Williams Cos.,reports,Energy,Oil & Gas Storage & Transportation,"Tulsa, Oklahoma",1975-03-31,107263,NaN
494,WLTW,Willis Towers Watson,reports,Financials,Insurance Brokers,"London, United Kingdom",2016-01-05,1140536,NaN
495,WYNN,Wynn Resorts Ltd,reports,Consumer Discretionary,Casinos & Gaming,"Paradise, Nevada",2008-11-14,1174922,NaN
496,XEL,Xcel Energy Inc,reports,Utilities,Multi-Utilities,"Minneapolis, Minnesota",NaN,72903,1909
497,XRX,Xerox,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Norwalk, Connecticut",NaN,108772,1906
498,XLNX,Xilinx,reports,Information Technology,Semiconductors,"San Jose, California",1999-11-08,743988,NaN
499,XYL,Xylem Inc.,reports,Industrials,Industrial Machinery,"White Plains, New York",2011-11-01,1524472,NaN
500,YUM,Yum! Brands Inc,reports,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,NaN
501,ZBRA,Zebra Technologies,reports,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
502,ZBH,Zimmer Biomet Holdings,reports,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,NaN
503,ZION,Zions Bancorp,reports,Financials,Regional Banks,"Salt Lake City, Utah",2001-06-22,109380,NaN
504,ZTS,Zoetis,reports,Health Care,Pharmaceuticals,"Florham Park, New Jersey",2013-06-21,1555280,NaN

In [218]:
ls_cik = table_2["CIK"]

In [219]:
len(ls_cik)

500

## Retrieve related filenames

In [220]:
import sqlite3
con = sqlite3.connect("/usr/local/ifs/gsb/EDGAR_HTTPS/edgar.db")
cur = con.cursor()

In [221]:
# Get column names
cur.execute("SELECT name FROM PRAGMA_TABLE_INFO('edgar')")
print("fetchall:")
result = cur.fetchall()
for r in result:
    print(r)

fetchall:
('cik',)
('company',)
('form',)
('date',)
('filename',)
('visited',)

In [222]:
# All forms
cur.execute("SELECT DISTINCT form FROM edgar")
print("fetchall:")
result = cur.fetchall()
for r in result:
    print(r)

fetchall:
('1',)
('1-A',)
('1-A POS',)
('1-A-W',)
('1-A-W/A',)
('1-A/A',)
('1-E',)
('1-E AD',)
('1-E/A',)
('1-K',)
('1-K/A',)
('1-SA',)
('1-SA/A',)
('1-U',)
('1-U/A',)
('1-Z',)
('1-Z-W',)
('1-Z/A',)
('1/A',)
('10-12B',)
('10-12B/A',)
('10-12G',)
('10-12G/A',)
('10-C',)
('10-C/A',)
('10-D',)
('10-D/A',)
('10-K',)
('10-K/A',)
('10-K405',)
('10-K405/A',)
('10-KSB',)
('10-KSB/A',)
('10-KT',)
('10-KT/A',)
('10-Q',)
('10-Q/A',)
('10-QSB',)
('10-QSB/A',)
('10-QT',)
('10-QT/A',)
('10KSB',)
('10KSB/A',)
('10KSB40',)
('10KSB40/A',)
('10KT405',)
('10KT405/A',)
('10QSB',)
('10QSB/A',)
('10SB12B',)
('10SB12B/A',)
('10SB12G',)
('10SB12G/A',)
('11-K',)
('11-K/A',)
('11-KT',)
('11-KT/A',)
('12G3-2B',)
('12G32BR',)
('13F-E',)
('13F-E/A',)
('13F-HR',)
('13F-HR/A',)
('13F-NT',)
('13F-NT/A',)
('13FCONP',)
('13FCONP/A',)
('144',)
('144/A',)
('15-12B',)
('15-12B/A',)
('15-12G',)
('15-12G/A',)
('15-15D',)
('15-15D/A',)
('15F-12B',)
('15F-12B/A',)
('15F-12G',)
('15F-12G/A',)
('15F-15D',)
('15F-15D/A',)
('18-12B',)
('18-K',)
('18-K/A',)
('19B-4',)
('19B-4E',)
('2-A',)
('2-A/A',)
('2-AF',)
('2-E',)
('2-E/A',)
('20-F',)
('20-F/A',)
('20FR12B',)
('20FR12B/A',)
('20FR12G',)
('20FR12G/A',)
('24F-1',)
('24F-2EL',)
('24F-2EL/A',)
('24F-2NT',)
('24F-2NT/A',)
('24F-2TM',)
('25',)
('25-NSE',)
('25-NSE/A',)
('25/A',)
('253G1',)
('253G2',)
('253G3',)
('253G4',)
('26',)
('3',)
('3/A',)
('305B2',)
('305B2/A',)
('34-12H',)
('35-APP',)
('35-APP/A',)
('35-CERT',)
('35-CERT/A',)
('39-304D',)
('39-304D/A',)
('39-310B',)
('4',)
('4/A',)
('40-17F1',)
('40-17F1/A',)
('40-17F2',)
('40-17F2/A',)
('40-17G',)
('40-17G/A',)
('40-17GCS',)
('40-202A',)
('40-202A/A',)
('40-203A',)
('40-203A/A',)
('40-205E',)
('40-205E/A',)
('40-206A',)
('40-206A/A',)
('40-24B2',)
('40-24B2/A',)
('40-33',)
('40-33/A',)
('40-6B',)
('40-6B/A',)
('40-6C',)
('40-6C/A',)
('40-8B25',)
('40-8F-2',)
('40-8F-2/A',)
('40-8F-A',)
('40-8F-A/A',)
('40-8F-B',)
('40-8F-B/A',)
('40-8F-L',)
('40-8F-L/A',)
('40-8F-M',)
('40-8F-M/A',)
('40-8FC',)
('40-8FC/A',)
('40-APP',)
('40-APP/A',)
('40-F',)
('40-F/A',)
('40-OIP',)
('40-OIP/A',)
('40-RPT',)
('40FR12B',)
('40FR12B/A',)
('40FR12G',)
('40FR12G/A',)
('424A',)
('424B1',)
('424B2',)
('424B3',)
('424B4',)
('424B5',)
('424B7',)
('424B8',)
('424H',)
('424H/A',)
('425',)
('485A24E',)
('485A24F',)
('485APOS',)
('485B24E',)
('485B24F',)
('485BPOS',)
('485BXT',)
('485BXTF',)
('486A24E',)
('486APOS',)
('486B24E',)
('486BPOS',)
('486BXT',)
('487',)
('497',)
('497AD',)
('497H2',)
('497J',)
('497K',)
('497K1',)
('497K2',)
('497K3A',)
('497K3B',)
('5',)
('5/A',)
('6-K',)
('6-K/A',)
('6B NTC',)
('6B ORDR',)
('8-A12B',)
('8-A12B/A',)
('8-A12G',)
('8-A12G/A',)
('8-B12B',)
('8-B12B/A',)
('8-B12G',)
('8-B12G/A',)
('8-K',)
('8-K/A',)
('8-K12B',)
('8-K12B/A',)
('8-K12G3',)
('8-K12G3/A',)
('8-K15D5',)
('8-K15D5/A',)
('8-M',)
('8A12BEF',)
('8A12BT',)
('8A12BT/A',)
('8F-2 NTC',)
('8F-2 ORDR',)
('9-M',)
('ABS-15G',)
('ABS-15G/A',)
('ABS-EE',)
('ABS-EE/A',)
('ADB',)
('ADN-MTL',)
('ADV-E',)
('ADV-H-C',)
('ADV-H-T',)
('ADV-NR',)
('ADV/A',)
('ADVCO',)
('ADVW',)
('AFDB',)
('AFDB/A',)
('ANNLRPT',)
('ANNLRPT/A',)
('APP NTC',)
('APP ORDR',)
('APP WD',)
('APP WD/A',)
('APP WDG',)
('ARS',)
('ARS/A',)
('ATS-N',)
('ATS-N-C',)
('ATS-N/CA',)
('ATS-N/MA',)
('ATS-N/UA',)
('AW',)
('AW WD',)
('BDCO',)
('BW-2',)
('BW-3',)
('C',)
('C-AR',)
('C-AR-W',)
('C-AR/A',)
('C-TR',)
('C-TR-W',)
('C-U',)
('C-U-W',)
('C-W',)
('C/A',)
('C/A-W',)
('CB',)
('CB/A',)
('CERT',)
('CERTAMX',)
('CERTARCA',)
('CERTBATS',)
('CERTBSE',)
('CERTCBO',)
('CERTCSE',)
('CERTNAS',)
('CERTNYS',)
('CERTPAC',)
('CERTPBS',)
('CFPORTAL',)
('CFPORTAL-W',)
('CFPORTAL/A',)
('CORRESP',)
('CT ORDER',)
('D',)
('D/A',)
('DEF 14A',)
('DEF 14C',)
('DEF-OC',)
('DEF13E3',)
('DEF13E3/A',)
('DEFA14A',)
('DEFA14C',)
('DEFC14A',)
('DEFC14C',)
('DEFM14A',)
('DEFM14C',)
('DEFN14A',)
('DEFR14A',)
('DEFR14C',)
('DEFS14A',)
('DEFS14C',)
('DEL AM',)
('DFAN14A',)
('DFRN14A',)
('DOS',)
('DOS/A',)
('DOSLTR',)
('DRS',)
('DRS/A',)
('DRSLTR',)
('DSTRBRPT',)
('DSTRBRPT/A',)
('EBRD',)
('EBRD/A',)
('EFFECT',)
('F-1',)
('F-1/A',)
('F-10',)
('F-10/A',)
('F-10EF',)
('F-10POS',)
('F-1MEF',)
('F-2',)
('F-2/A',)
('F-3',)
('F-3/A',)
('F-3ASR',)
('F-3D',)
('F-3DPOS',)
('F-3MEF',)
('F-4',)
('F-4 POS',)
('F-4/A',)
('F-4MEF',)
('F-6',)
('F-6 POS',)
('F-6/A',)
('F-6EF',)
('F-7',)
('F-7 POS',)
('F-7/A',)
('F-8',)
('F-8 POS',)
('F-8/A',)
('F-80',)
('F-80/A',)
('F-80POS',)
('F-9',)
('F-9 POS',)
('F-9/A',)
('F-9EF',)
('F-N',)
('F-N/A',)
('F-X',)
('F-X/A',)
('FOCUSN',)
('FOCUSN/A',)
('FWP',)
('G-405',)
('G-405/A',)
('G-405N',)
('G-405N/A',)
('G-FIN',)
('G-FIN/A',)
('G-FINW',)
('IADB',)
('ID-NEWCIK',)
('IFC',)
('IRANNOTICE',)
('MA',)
('MA-A',)
('MA-I',)
('MA-I/A',)
('MA-W',)
('MA/A',)
('MSD',)
('MSD/A',)
('MSDCO',)
('MSDW',)
('N-1',)
('N-1/A',)
('N-14',)
('N-14 8C',)
('N-14 8C/A',)
('N-14/A',)
('N-14AE',)
('N-14AE/A',)
('N-14MEF',)
('N-18F1',)
('N-18F1/A',)
('N-1A',)
('N-1A EL',)
('N-1A EL/A',)
('N-1A/A',)
('N-2',)
('N-2/A',)
('N-23C-1',)
('N-23C-1/A',)
('N-23C-2',)
('N-23C-2/A',)
('N-23C3A',)
('N-23C3A/A',)
('N-23C3B',)
('N-23C3B/A',)
('N-23C3C',)
('N-23C3C/A',)
('N-27D-1',)
('N-2MEF',)
('N-3',)
('N-3 EL',)
('N-3 EL/A',)
('N-3/A',)
('N-30B-2',)
('N-30D',)
('N-30D/A',)
('N-4',)
('N-4 EL',)
('N-4 EL/A',)
('N-4/A',)
('N-5',)
('N-5/A',)
('N-54A',)
('N-54A/A',)
('N-54C',)
('N-54C/A',)
('N-6',)
('N-6/A',)
('N-6F',)
('N-6F/A',)
('N-8A',)
('N-8A/A',)
('N-8B-2',)
('N-8B-2/A',)
('N-8B-4',)
('N-8F',)
('N-8F NTC',)
('N-8F ORDR',)
('N-8F/A',)
('N-CEN',)
('N-CEN/A',)
('N-CR',)
('N-CR/A',)
('N-CSR',)
('N-CSR/A',)
('N-CSRS',)
('N-CSRS/A',)
('N-MFP',)
('N-MFP/A',)
('N-MFP1',)
('N-MFP1/A',)
('N-MFP2',)
('N-MFP2/A',)
('N-PX',)
('N-PX/A',)
('N-Q',)
('N-Q/A',)
('N14AE24',)
('N14AE24/A',)
('N14EL24',)
('N14EL24/A',)
('NO ACT',)
('NPORT-EX',)
('NPORT-EX/A',)
('NRSRO-CE',)
('NRSRO-CE/A',)
('NRSRO-UPD',)
('NSAR-A',)
('NSAR-A/A',)
('NSAR-AT',)
('NSAR-AT/A',)
('NSAR-B',)
('NSAR-B/A',)
('NSAR-BT',)
('NSAR-BT/A',)
('NSAR-U',)
('NSAR-U/A',)
('NT 10-D',)
('NT 10-D/A',)
('NT 10-K',)
('NT 10-K/A',)
('NT 10-Q',)
('NT 10-Q/A',)
('NT 11-K',)
('NT 11-K/A',)
('NT 15D2',)
('NT 15D2/A',)
('NT 20-F',)
('NT 20-F/A',)
('NT N-CEN',)
('NT N-MFP',)
('NT N-MFP1',)
('NT N-MFP2',)
('NT NPORT-EX',)
('NT-NCEN',)
('NT-NCEN/A',)
('NT-NCSR',)
('NT-NCSR/A',)
('NT-NSAR',)
('NT-NSAR/A',)
('NTFNCEN',)
('NTFNCSR',)
('NTFNSAR',)
('NTN 10D',)
('NTN 10K',)
('NTN 10Q',)
('NTN 11K',)
('NTN 20F',)
('NTN15D2',)
('OIP NTC',)
('OIP ORDR',)
('POS 8C',)
('POS AM',)
('POS AMC',)
('POS AMI',)
('POS EX',)
('POS462B',)
('POS462C',)
('POSASR',)
('PRE 14A',)
('PRE 14C',)
('PRE13E3',)
('PRE13E3/A',)
('PREA14A',)
('PREA14C',)
('PREC14A',)
('PREC14C',)
('PREM14A',)
('PREM14C',)
('PREN14A',)
('PRER14A',)
('PRER14C',)
('PRES14A',)
('PRES14C',)
('PRRN14A',)
('PX14A6G',)
('PX14A6N',)
('QRTLYRPT',)
('QRTLYRPT/A',)
('QUALIF',)
('REG-NR',)
('REG-NR/A',)
('REGDEX',)
('REGDEX/A',)
('REVOKED',)
('RW',)
('RW WD',)
('S-1',)
('S-1/A',)
('S-11',)
('S-11/A',)
('S-11MEF',)
('S-1MEF',)
('S-2',)
('S-2/A',)
('S-20',)
('S-20/A',)
('S-2MEF',)
('S-3',)
('S-3/A',)
('S-3ASR',)
('S-3D',)
('S-3D/A',)
('S-3DPOS',)
('S-3MEF',)
('S-4',)
('S-4 POS',)
('S-4/A',)
('S-4EF',)
('S-4EF/A',)
('S-4MEF',)
('S-6',)
('S-6/A',)
('S-6EL24',)
('S-6EL24/A',)
('S-8',)
('S-8 POS',)
('S-8/A',)
('S-B',)
('S-B/A',)
('S-BMEF',)
('SB-1',)
('SB-1/A',)
('SB-1MEF',)
('SB-2',)
('SB-2/A',)
('SB-2MEF',)
('SC 13D',)
('SC 13D/A',)
('SC 13E1',)
('SC 13E1/A',)
('SC 13E3',)
('SC 13E3/A',)
('SC 13E4',)
('SC 13E4/A',)
('SC 13G',)
('SC 13G/A',)
('SC 14D1',)
('SC 14D1/A',)
('SC 14D9',)
('SC 14D9/A',)
('SC 14F1',)
('SC 14F1/A',)
('SC 14N',)
('SC 14N/A',)
('SC TO-C',)
('SC TO-I',)
('SC TO-I/A',)
('SC TO-T',)
('SC TO-T/A',)
('SC13E4F',)
('SC13E4F/A',)
('SC14D1F',)
('SC14D1F/A',)
('SC14D9C',)
('SC14D9F',)
('SC14D9F/A',)
('SD',)
('SD/A',)
('SDR',)
('SDR/A',)
('SE',)
('SEC ACTION',)
('SEC STAFF ACTION',)
('SEC STAFF LETTER',)
('SF-1',)
('SF-1/A',)
('SF-3',)
('SF-3/A',)
('SL',)
('SP 15D2',)
('SP 15D2/A',)
('STOP ORDER',)
('SUPPL',)
('T-3',)
('T-3/A',)
('TA-1',)
('TA-1/A',)
('TA-2',)
('TA-2/A',)
('TA-W',)
('TACO',)
('TH',)
('TTW',)
('TTW/A',)
('U-1',)
('U-1/A',)
('U-12-IA',)
('U-12-IA/A',)
('U-12-IB',)
('U-12-IB/A',)
('U-13-60',)
('U-13-60/A',)
('U-13E-1',)
('U-33-S',)
('U-33-S/A',)
('U-3A-2',)
('U-3A-2/A',)
('U-3A3-1',)
('U-57',)
('U-57/A',)
('U-6B-2',)
('U-6B-2/A',)
('U-7D',)
('U-7D/A',)
('U-9C-3',)
('U-9C-3/A',)
('U5A',)
('U5A/A',)
('U5B',)
('U5B/A',)
('U5S',)
('U5S/A',)
('UNDER',)
('UNDER/A',)
('UPLOAD',)
('WDL-REQ',)
('X-17A-5',)
('X-17A-5/A',)

In [223]:
# Example output
cur.execute("SELECT * FROM edgar limit 1")
print("fetchall:")
result = cur.fetchall()
for r in result:
    print(r)

fetchall:
('1000032', 'BINCH JAMES G', '4', '2014-06-03', 'edgar/data/1000032/0001181431-14-022442.txt', 200)

In [224]:
# Try get one company's 10-K form
cur.execute("select filename from edgar where cik = 66740 and date > '2009-12-31'and form = '10-K'  limit 30")
print("fetchall:")
result = cur.fetchall()
for r in result:
    print(r[0])

fetchall:
edgar/data/66740/0001104659-10-007295.txt
edgar/data/66740/0001104659-11-007845.txt
edgar/data/66740/0001104659-12-010566.txt
edgar/data/66740/0001104659-13-010881.txt
edgar/data/66740/0001104659-14-009773.txt
edgar/data/66740/0001104659-15-009560.txt
edgar/data/66740/0001558370-16-003162.txt
edgar/data/66740/0001558370-17-000479.txt
edgar/data/66740/0001558370-18-000535.txt
edgar/data/66740/0001558370-19-000470.txt

In [225]:
# Hmmmmm there's 10K405
cur.execute("select filename from edgar where cik = 66740 and date > '2009-12-31'and form = '10-K405'  limit 30")
print("fetchall:")
result = cur.fetchall()
for r in result:
    print(r)

fetchall:

In [260]:
# Retrieve all the filenames
dict_cik_filename = dict()
for i in ls_cik:
    ls_tmp = []
    cur.execute("select filename from edgar where cik = {0} and date >= '2010-01-01'and date <= '2019-12-31' and form like'%10-K'  limit 30".format(i))
    result = cur.fetchall()
    for r in result:
        ls_tmp.append(r[0])
    dict_cik_filename[i] = ls_tmp

In [263]:
without_like = []
for value in dict_cik_filename.values():
    without_like.append(value)

In [257]:
# Retrieve all the filenames
cur.execute("select filename from edgar where cik in ('66740', '1800', '1551152', '815094', '1467373', '718877', '796343', '2488', '1158449', '874761', '4977', '1090872', '2969', '1086222', '766421', '915913', '1035443', '899866', '1097149', '1579241', '1578845', '1101215', '352541', '899051', '1652044', '764180', '1018724', '1748790', '1002910', '6201', '4904', '4962', '5272', '1053507', '1410636', '820027', '1140859', '1037868', '318154', '820313', '6281', '1013462', '1156039', '315293', '91142', '6769', '922864', '320193', '6951', '1521332', '7084', '4281', '1596532', '354190', '1267238', '731802', '732717', '769397', '8670', '866787', '915912', '8818', '1701605', '9389', '70858', '1390777', '10456', '10795', '1067983', '764478', '875045', '1364742', '12927', '1075531', '908255', '1037540', '885725', '14272', '1730168', '1383312', '14693', '1043277', '858470', '813672', '16732', '927628', '1530721', '721371', '1170010', '815097', '18230', '1374310', '1138118', '1402057', '1306830', '1071739', '1130310', '18926', '804753', '1324404', '316709', '1091667', '93410', '1058090', '896159', '313927', '701221', '1168054', '20286', '723254', '858877', '831001', '759944', '877890', '21076', '1156375', '811156', '21344', '1058290', '21665', '1166691', '28412', '23217', '1358071', '1163165', '1047862', '16918', '711404', '900075', '24741', '1755672', '909832', '1024305', '1051470', '277948', '26172', '64803', '882184', '313616', '940944', '927066', '315189', '27904', '818479', '1090012', '1539838', '1297996', '1393612', '1437107', '1001082', '29534', '935703', '715957', '29905', '1751788', '936340', '1326160', '783280', '1666700', '1688568', '1015780', '915389', '1551182', '1065088', '31462', '827052', '1099800', '712515', '32604', '65984', '821189', '33185', '1101239', '906107', '920522', '1001250', '1711269', '72741', '1095073', '1109357', '1324424', '746515', '1289490', '34088', '1048695', '1326801', '815556', '34903', '1048911', '1136893', '35527', '1031296', '1132979', '798354', '1175454', '354908', '30625', '37785', '37996', '1262039', '1659166', '1519751', '1308161', '38777', '831259', '39911', '1121788', '749251', '40533', '40545', '40704', '1467858', '40987', '882095', '320335', '1123360', '886982', '277135', '12659', '45012', '1359841', '793952', '874766', '46080', '860730', '765880', '46765', '1000228', '47111', '4447', '1645590', '1585689', '48039', '859737', '354950', '773840', '48465', '1070750', '47217', '49071', '49196', '1501585', '832101', '874716', '1598014', '49826', '1110803', '1466258', '50863', '1571949', '51143', '879169', '51434', '51644', '51253', '896878', '1035267', '914208', '1111928', '1478242', '1020569', '779152', '52988', '728535', '91419', '200406', '833444', '19617', '1043604', '54480', '55067', '91576', '1601046', '55785', '879101', '1506307', '319201', '885639', '1637459', '56873', '701985', '202058', '920148', '707549', '1679273', '1300514', '58492', '1336920', '920760', '59478', '59558', '1707925', '1335258', '1065696', '936468', '60086', '60667', '1489393', '36270', '794367', '101778', '1510295', '1278021', '1048286', '62709', '916076', '62996', '1141391', '63754', '743316', '63908', '927653', '1613103', '310158', '1099219', '1037646', '789570', '827054', '723125', '789019', '912595', '851968', '24545', '1103982', '865752', '1059556', '895421', '1285785', '68505', '1408198', '1623613', '1120193', '1021860', '1002047', '1065280', '814453', '1164727', '1564708', '753308', '1492633', '320187', '1111711', '72207', '72333', '702165', '73124', '1133421', '849399', '1513761', '1013871', '73309', '1045810', '906163', '898173', '797468', '878927', '29989', '1039684', '1341439', '75362', '75677', '76334', '723531', '1633917', '77360', '1378946', '77476', '31791', '1585364', '78003', '1413329', '1534701', '764622', '1038357', '713676', '79879', '922224', '1126328', '80424', '80661', '1045609', '1137774', '788784', '1393311', '822416', '78239', '1604778', '1050915', '804328', '1022079', '1037038', '720005', '1047122', '726728', '910606', '872589', '1281761', '1060391', '943819', '315213', '1024478', '84839', '882835', '745732', '884887', '64040', '1108524', '1034054', '87347', '1137789', '1012100', '1032208', '1373715', '89800', '1063761', '4127', '1040971', '91440', '92122', '92380', '93556', '829224', '93751', '1757898', '310764', '719739', '1601712', '883241', '96021', '1283699', '1113169', '946581', '1116132', '27419', '1385157', '1681459', '96943', '97476', '217346', '97745', '98246', '109198', '916365', '1260221', '86312', '92230', '1418091', '100493', '74208', '1403568', '36104', '1336917', '100885', '100517', '731766', '1090727', '1067701', '101829', '352915', '5513', '103379', '1035002', '203527', '740260', '1014473', '1442145', '732712', '875320', '1339947', '1403161', '899689', '1396009', '11544', '943452', '104169', '1618921', '1001039', '823768', '1000697', '783325', '1279363', '72971', '766704', '106040', '1365135', '1636023', '106535', '106640', '107263', '1140536', '1174922', '72903', '108772', '743988', '1524472', '1041061', '877212', '1136869', '109380', '1555280') and date >= '2010-01-01'and date <= '2019-12-31' and form like'%10-K'")
result = cur.fetchall()

In [258]:
len(result)

4673

In [259]:
with_like = result

In [239]:
# Actual file number in the datebase using 10-k as a filter
ls_actual_num = [len(i) for i in dict_cik_filename.values()]

In [240]:
sum(ls_actual_num)

4655

In [229]:
pd.isna(table[0].loc[0,"Date first added"])

True

In [230]:
table[0].loc[1,"Date first added"]

'1964-03-31'

In [231]:
date = table[0]["Date first added"]

In [232]:
import datetime
# date_time_str = '2018-06-29 08:15:27.243860'
# date_time_obj = datetime.datetime.strptime(date_time_str, '%Y-%m-%d %H:%M:%S.%f')
# date_time_obj
dict_correct_num = dict()
ls_correct_num = []
for i,date_time_str in zip(ls_cik,date):
    #print(i,date_time_str)
    if pd.isna(date_time_str):
        correct_num = 10
    else:
        if len(date_time_str) == 10:
            date_time_obj = datetime.datetime.strptime(date_time_str, '%Y-%m-%d')
            year = date_time_obj.year
        else:
            date_time_obj = datetime.datetime.strptime(date_time_str, '%Y')
            year = date_time_obj.year
        if year < 2010:
            correct_num = 10
        else:
            correct_num = 2020 - year
    ls_correct_num.append(correct_num)
    dict_correct_num[i] = correct_num

In [233]:
ls_correct_num

[10,
 10,
 8,
 2,
 9,
 5,
 10,
 3,
 5,
 10,
 10,
 10,
 10,
 10,
 4,
 4,
 3,
 8,
 3,
 7,
 10,
 7,
 4,
 10,
 6,
 10,
 10,
 10,
 1,
 10,
 5,
 10,
 10,
 10,
 10,
 4,
 10,
 10,
 7,
 10,
 10,
 10,
 3,
 10,
 10,
 3,
 10,
 10,
 10,
 10,
 8,
 10,
 10,
 2,
 4,
 10,
 1,
 10,
 10,
 10,
 10,
 10,
 10,
 3,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 9,
 10,
 10,
 9,
 10,
 10,
 10,
 6,
 2,
 10,
 10,
 10,
 3,
 10,
 10,
 7,
 10,
 10,
 10,
 10,
 3,
 10,
 1,
 2,
 4,
 10,
 10,
 10,
 10,
 10,
 4,
 10,
 9,
 10,
 5,
 10,
 6,
 10,
 10,
 10,
 10,
 4,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 5,
 10,
 10,
 4,
 10,
 10,
 10,
 4,
 2,
 10,
 1,
 10,
 4,
 8,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 7,
 10,
 10,
 2,
 4,
 10,
 10,
 6,
 3,
 8,
 9,
 10,
 10,
 1,
 10,
 10,
 3,
 10,
 3,
 10,
 10,
 10,
 10,
 10,
 10,
 9,
 10,
 10,
 10,
 10,
 10,
 5,
 10,
 6,
 10,
 2,
 10,
 3,
 10,
 10,
 10,
 4,
 10,
 10,
 7,
 10,
 4,
 10,
 10,
 10,
 10,
 1,
 10,
 2,
 10,
 10,
 10,
 10,
 2,
 4,
 4,
 7,
 5,
 10,
 10,
 10,
 8,
 3,
 10,
 10,
 10,
 7,
 10,
 10,
 10,
 4,
 10,
 10,
 10,
 10,
 5,
 10,
 10,
 10,
 5,
 10,
 10,
 5,
 10,
 10,
 5,
 3,
 2,
 4,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 2,
 1,
 3,
 3,
 10,
 5,
 10,
 10,
 10,
 10,
 3,
 10,
 10,
 10,
 10,
 10,
 10,
 2,
 3,
 10,
 2,
 10,
 5,
 10,
 10,
 10,
 10,
 10,
 7,
 10,
 10,
 2,
 10,
 10,
 8,
 10,
 10,
 5,
 10,
 10,
 10,
 10,
 8,
 2,
 1,
 10,
 1,
 10,
 10,
 10,
 10,
 1,
 4,
 10,
 10,
 10,
 8,
 10,
 10,
 10,
 9,
 1,
 10,
 10,
 6,
 10,
 10,
 10,
 2,
 10,
 10,
 10,
 10,
 10,
 4,
 3,
 10,
 10,
 10,
 4,
 7,
 10,
 8,
 8,
 10,
 10,
 9,
 10,
 2,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 7,
 5,
 10,
 7,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 3,
 10,
 10,
 10,
 1,
 10,
 10,
 1,
 10,
 10,
 10,
 10,
 3,
 10,
 10,
 5,
 8,
 10,
 10,
 10,
 9,
 10,
 10,
 8,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 7,
 5,
 10,
 10,
 10,
 10,
 3,
 10,
 5,
 3,
 7,
 10,
 10,
 3,
 10,
 10,
 2,
 10,
 10,
 6,
 10,
 10,
 3,
 10,
 8,
 10,
 10,
 1,
 10,
 10,
 5,
 5,
 10,
 10,
 10,
 10,
 10,
 10,
 1,
 10,
 2,
 5,
 3,
 10,
 1,
 10,
 2,
 10,
 10,
 9,
 10,
 1,
 10,
 10,
 10,
 10,
 10,
 6,
 4,
 10,
 10,
 2,
 10,
 4,
 4,
 10,
 4,
 6,
 10,
 5,
 10,
 10,
 6,
 10,
 6,
 10,
 10,
 10,
 10,
 10,
 10,
 5,
 10,
 7,
 10,
 10,
 10,
 10,
 1,
 1,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 4,
 10,
 10,
 10,
 10,
 9]

In [234]:
sum(ls_correct_num)

4080

In [235]:
df_compare_num = pd.DataFrame({"cik":ls_cik,"correct":ls_correct_num,"actual":ls_actual_num})
df_compare_num

         cik  correct  actual
0      66740       10      10
1       1800       10      10
2    1551152        8       7
3     815094        2      10
4    1467373        9       9
5     718877        5      10
6     796343       10      10
7       2488        3      10
8    1158449        5      10
9     874761       10      10
10      4977       10      10
11   1090872       10       9
12      2969       10       9
13   1086222       10      10
14    766421        4      10
15    915913        4      10
16   1035443        3      10
17    899866        8      10
18   1097149        3      10
19   1579241        7       6
20   1578845       10       6
21   1101215        7      10
22    352541        4      10
23    899051       10      10
24   1652044        6       4
26    764180       10      10
27   1018724       10      10
28   1748790       10       0
29   1002910        1      10
30      6201       10      10
..       ...      ...     ...
475   899689        5      10
476  1396009       10      10
477    11544        7      10
478   943452       10      10
479   104169       10      10
480  1618921       10       4
481  1001039       10       9
482   823768        1      10
483  1000697        1      10
484   783325       10      10
485  1279363       10      10
486    72971       10      10
487   766704       10      10
488   106040       10       9
489  1365135       10      10
490  1636023       10       3
491   106535       10      10
492   106640       10      10
493   107263       10      10
494  1140536       10      10
495  1174922       10      10
496    72903       10      10
497   108772       10      10
498   743988       10      10
499  1524472        4       8
500  1041061       10      10
501   877212       10      10
502  1136869       10      10
503   109380       10      10
504  1555280        9       7

[500 rows x 3 columns]

In [249]:
ls_cik_str = [str(i)for i in ls_cik.tolist()]

In [251]:
print(ls_cik_str)

['66740', '1800', '1551152', '815094', '1467373', '718877', '796343', '2488', '1158449', '874761', '4977', '1090872', '2969', '1086222', '766421', '915913', '1035443', '899866', '1097149', '1579241', '1578845', '1101215', '352541', '899051', '1652044', '764180', '1018724', '1748790', '1002910', '6201', '4904', '4962', '5272', '1053507', '1410636', '820027', '1140859', '1037868', '318154', '820313', '6281', '1013462', '1156039', '315293', '91142', '6769', '922864', '320193', '6951', '1521332', '7084', '4281', '1596532', '354190', '1267238', '731802', '732717', '769397', '8670', '866787', '915912', '8818', '1701605', '9389', '70858', '1390777', '10456', '10795', '1067983', '764478', '875045', '1364742', '12927', '1075531', '908255', '1037540', '885725', '14272', '1730168', '1383312', '14693', '1043277', '858470', '813672', '16732', '927628', '1530721', '721371', '1170010', '815097', '18230', '1374310', '1138118', '1402057', '1306830', '1071739', '1130310', '18926', '804753', '1324404', '316709', '1091667', '93410', '1058090', '896159', '313927', '701221', '1168054', '20286', '723254', '858877', '831001', '759944', '877890', '21076', '1156375', '811156', '21344', '1058290', '21665', '1166691', '28412', '23217', '1358071', '1163165', '1047862', '16918', '711404', '900075', '24741', '1755672', '909832', '1024305', '1051470', '277948', '26172', '64803', '882184', '313616', '940944', '927066', '315189', '27904', '818479', '1090012', '1539838', '1297996', '1393612', '1437107', '1001082', '29534', '935703', '715957', '29905', '1751788', '936340', '1326160', '783280', '1666700', '1688568', '1015780', '915389', '1551182', '1065088', '31462', '827052', '1099800', '712515', '32604', '65984', '821189', '33185', '1101239', '906107', '920522', '1001250', '1711269', '72741', '1095073', '1109357', '1324424', '746515', '1289490', '34088', '1048695', '1326801', '815556', '34903', '1048911', '1136893', '35527', '1031296', '1132979', '798354', '1175454', '354908', '30625', '37785', '37996', '1262039', '1659166', '1519751', '1308161', '38777', '831259', '39911', '1121788', '749251', '40533', '40545', '40704', '1467858', '40987', '882095', '320335', '1123360', '886982', '277135', '12659', '45012', '1359841', '793952', '874766', '46080', '860730', '765880', '46765', '1000228', '47111', '4447', '1645590', '1585689', '48039', '859737', '354950', '773840', '48465', '1070750', '47217', '49071', '49196', '1501585', '832101', '874716', '1598014', '49826', '1110803', '1466258', '50863', '1571949', '51143', '879169', '51434', '51644', '51253', '896878', '1035267', '914208', '1111928', '1478242', '1020569', '779152', '52988', '728535', '91419', '200406', '833444', '19617', '1043604', '54480', '55067', '91576', '1601046', '55785', '879101', '1506307', '319201', '885639', '1637459', '56873', '701985', '202058', '920148', '707549', '1679273', '1300514', '58492', '1336920', '920760', '59478', '59558', '1707925', '1335258', '1065696', '936468', '60086', '60667', '1489393', '36270', '794367', '101778', '1510295', '1278021', '1048286', '62709', '916076', '62996', '1141391', '63754', '743316', '63908', '927653', '1613103', '310158', '1099219', '1037646', '789570', '827054', '723125', '789019', '912595', '851968', '24545', '1103982', '865752', '1059556', '895421', '1285785', '68505', '1408198', '1623613', '1120193', '1021860', '1002047', '1065280', '814453', '1164727', '1564708', '753308', '1492633', '320187', '1111711', '72207', '72333', '702165', '73124', '1133421', '849399', '1513761', '1013871', '73309', '1045810', '906163', '898173', '797468', '878927', '29989', '1039684', '1341439', '75362', '75677', '76334', '723531', '1633917', '77360', '1378946', '77476', '31791', '1585364', '78003', '1413329', '1534701', '764622', '1038357', '713676', '79879', '922224', '1126328', '80424', '80661', '1045609', '1137774', '788784', '1393311', '822416', '78239', '1604778', '1050915', '804328', '1022079', '1037038', '720005', '1047122', '726728', '910606', '872589', '1281761', '1060391', '943819', '315213', '1024478', '84839', '882835', '745732', '884887', '64040', '1108524', '1034054', '87347', '1137789', '1012100', '1032208', '1373715', '89800', '1063761', '4127', '1040971', '91440', '92122', '92380', '93556', '829224', '93751', '1757898', '310764', '719739', '1601712', '883241', '96021', '1283699', '1113169', '946581', '1116132', '27419', '1385157', '1681459', '96943', '97476', '217346', '97745', '98246', '109198', '916365', '1260221', '86312', '92230', '1418091', '100493', '74208', '1403568', '36104', '1336917', '100885', '100517', '731766', '1090727', '1067701', '101829', '352915', '5513', '103379', '1035002', '203527', '740260', '1014473', '1442145', '732712', '875320', '1339947', '1403161', '899689', '1396009', '11544', '943452', '104169', '1618921', '1001039', '823768', '1000697', '783325', '1279363', '72971', '766704', '106040', '1365135', '1636023', '106535', '106640', '107263', '1140536', '1174922', '72903', '108772', '743988', '1524472', '1041061', '877212', '1136869', '109380', '1555280']

In [246]:
print(ls_cik.tolist())

[66740, 1800, 1551152, 815094, 1467373, 718877, 796343, 2488, 1158449, 874761, 4977, 1090872, 2969, 1086222, 766421, 915913, 1035443, 899866, 1097149, 1579241, 1578845, 1101215, 352541, 899051, 1652044, 764180, 1018724, 1748790, 1002910, 6201, 4904, 4962, 5272, 1053507, 1410636, 820027, 1140859, 1037868, 318154, 820313, 6281, 1013462, 1156039, 315293, 91142, 6769, 922864, 320193, 6951, 1521332, 7084, 4281, 1596532, 354190, 1267238, 731802, 732717, 769397, 8670, 866787, 915912, 8818, 1701605, 9389, 70858, 1390777, 10456, 10795, 1067983, 764478, 875045, 1364742, 12927, 1075531, 908255, 1037540, 885725, 14272, 1730168, 1383312, 14693, 1043277, 858470, 813672, 16732, 927628, 1530721, 721371, 1170010, 815097, 18230, 1374310, 1138118, 1402057, 1306830, 1071739, 1130310, 18926, 804753, 1324404, 316709, 1091667, 93410, 1058090, 896159, 313927, 701221, 1168054, 20286, 723254, 858877, 831001, 759944, 877890, 21076, 1156375, 811156, 21344, 1058290, 21665, 1166691, 28412, 23217, 1358071, 1163165, 1047862, 16918, 711404, 900075, 24741, 1755672, 909832, 1024305, 1051470, 277948, 26172, 64803, 882184, 313616, 940944, 927066, 315189, 27904, 818479, 1090012, 1539838, 1297996, 1393612, 1437107, 1001082, 29534, 935703, 715957, 29905, 1751788, 936340, 1326160, 783280, 1666700, 1688568, 1015780, 915389, 1551182, 1065088, 31462, 827052, 1099800, 712515, 32604, 65984, 821189, 33185, 1101239, 906107, 920522, 1001250, 1711269, 72741, 1095073, 1109357, 1324424, 746515, 1289490, 34088, 1048695, 1326801, 815556, 34903, 1048911, 1136893, 35527, 1031296, 1132979, 798354, 1175454, 354908, 30625, 37785, 37996, 1262039, 1659166, 1519751, 1308161, 38777, 831259, 39911, 1121788, 749251, 40533, 40545, 40704, 1467858, 40987, 882095, 320335, 1123360, 886982, 277135, 12659, 45012, 1359841, 793952, 874766, 46080, 860730, 765880, 46765, 1000228, 47111, 4447, 1645590, 1585689, 48039, 859737, 354950, 773840, 48465, 1070750, 47217, 49071, 49196, 1501585, 832101, 874716, 1598014, 49826, 1110803, 1466258, 50863, 1571949, 51143, 879169, 51434, 51644, 51253, 896878, 1035267, 914208, 1111928, 1478242, 1020569, 779152, 52988, 728535, 91419, 200406, 833444, 19617, 1043604, 54480, 55067, 91576, 1601046, 55785, 879101, 1506307, 319201, 885639, 1637459, 56873, 701985, 202058, 920148, 707549, 1679273, 1300514, 58492, 1336920, 920760, 59478, 59558, 1707925, 1335258, 1065696, 936468, 60086, 60667, 1489393, 36270, 794367, 101778, 1510295, 1278021, 1048286, 62709, 916076, 62996, 1141391, 63754, 743316, 63908, 927653, 1613103, 310158, 1099219, 1037646, 789570, 827054, 723125, 789019, 912595, 851968, 24545, 1103982, 865752, 1059556, 895421, 1285785, 68505, 1408198, 1623613, 1120193, 1021860, 1002047, 1065280, 814453, 1164727, 1564708, 753308, 1492633, 320187, 1111711, 72207, 72333, 702165, 73124, 1133421, 849399, 1513761, 1013871, 73309, 1045810, 906163, 898173, 797468, 878927, 29989, 1039684, 1341439, 75362, 75677, 76334, 723531, 1633917, 77360, 1378946, 77476, 31791, 1585364, 78003, 1413329, 1534701, 764622, 1038357, 713676, 79879, 922224, 1126328, 80424, 80661, 1045609, 1137774, 788784, 1393311, 822416, 78239, 1604778, 1050915, 804328, 1022079, 1037038, 720005, 1047122, 726728, 910606, 872589, 1281761, 1060391, 943819, 315213, 1024478, 84839, 882835, 745732, 884887, 64040, 1108524, 1034054, 87347, 1137789, 1012100, 1032208, 1373715, 89800, 1063761, 4127, 1040971, 91440, 92122, 92380, 93556, 829224, 93751, 1757898, 310764, 719739, 1601712, 883241, 96021, 1283699, 1113169, 946581, 1116132, 27419, 1385157, 1681459, 96943, 97476, 217346, 97745, 98246, 109198, 916365, 1260221, 86312, 92230, 1418091, 100493, 74208, 1403568, 36104, 1336917, 100885, 100517, 731766, 1090727, 1067701, 101829, 352915, 5513, 103379, 1035002, 203527, 740260, 1014473, 1442145, 732712, 875320, 1339947, 1403161, 899689, 1396009, 11544, 943452, 104169, 1618921, 1001039, 823768, 1000697, 783325, 1279363, 72971, 766704, 106040, 1365135, 1636023, 106535, 106640, 107263, 1140536, 1174922, 72903, 108772, 743988, 1524472, 1041061, 877212, 1136869, 109380, 1555280]

In [236]:
cur.execute("select filename from edgar where cik = 1551152 and date > '2009-12-31'and form = '10-K'  limit 30")
print("fetchall:")
result = cur.fetchall()
for r in result:
    print(r[0])

fetchall:
edgar/data/1551152/0001047469-13-002827.txt
edgar/data/1551152/0001047469-14-001154.txt
edgar/data/1551152/0001047469-15-000995.txt
edgar/data/1551152/0001047469-16-010239.txt
edgar/data/1551152/0001551152-17-000004.txt
edgar/data/1551152/0001551152-18-000014.txt
edgar/data/1551152/0001551152-19-000008.txt

In [237]:
cur.execute("select filename from edgar where cik = 1551152 and date > '2009-12-31' and form = '10-K/A' limit 50")
print("fetchall:")
result = cur.fetchall()
for r in result:
    print(r[0])

fetchall:
edgar/data/1551152/0001047469-13-004011.txt